In [ ]:
import os
import sys
from time import sleep

import GCode
import GRBL
import numpy as np

# Draw a Brick Pattern

> Standard bricks. The standard co-ordinating size for brickwork is 225 mm x 112.5 mm x 75 mm (length x depth x height). This includes 10 mm mortar joints, and so the standard size for a brick itself is 215 mm x 102.5 mm x 65 mm (length x depth x height).

Attempt at programmatically making a brick pattern. 

"Napkin" scratches.

![](http://luckofthedraw.fun/.imgs/brick_0003.jpeg)

Drawn by hand. ~18mm brick height.

![](http://luckofthedraw.fun/.imgs/brick_0001.jpeg)



In [9]:
BrickHeight = 65
BrickLength = 225
BrickDepth = 102.5

BrickRatio = 215 / 65
BrickRatio


3.3076923076923075

In [10]:
BlockHeight = 89.0
BlockLength = 176.0


In [11]:
N_BrickRows = 5


In [12]:
H_Block_Brick = BlockHeight / N_BrickRows


In [13]:
L_Block_Brick = H_Block_Brick * BrickRatio


In [14]:
H_Block_Brick


17.8

In [15]:
L_Block_Brick


58.87692307692308

# Code:

In [17]:
cnc = GRBL.GRBL(port="/dev/cnc_3018")
cnc.reset()
cnc.laser_mode = 1


ok


In [18]:
print(cnc.laser_mode)


1.0


In [19]:
cnc.home()


In [6]:
cnc.status


'<Idle|MPos:-259.000,-174.000,-1.000|Bf:15,127|FS:0,0|WCO:0.000,0.000,0.000>'

In [21]:
cnc.cmd("G28")


['ok', 'ok']

In [22]:
def init():
    program = GCode.GCode()
    program.G0(F=500)
    program.G1(F=200)
    program.M3(S=1)
    program.G28()
    program.G21()  # Metric Units
    program.G90()  # Absolute positioning.
    program.G92(X=0, Y=0, Z=0)
    return program


In [27]:
np.arange(H_Block_Brick, BlockHeight, H_Block_Brick)


array([17.8, 35.6, 53.4, 71.2])

In [34]:
Brick_Line = np.array([[0, H_Block_Brick], [BlockLength, H_Block_Brick]])
Brick_Line


array([[  0. ,  17.8],
       [176. ,  17.8]])

In [35]:
Brick_Line.shape[0]


2

In [40]:
for row_idx in range(Brick_Line.shape[0]):
    print(Brick_Line[:, row_idx])
    break


[  0. 176.]


In [50]:
default_line = np.array([[0, 0], [10, 5]])


In [96]:
default_line


array([[ 0,  0],
       [10,  5]])

Draw a line from (0, 0) to (10, 5).

In [97]:
prog = GCode.GCode()


def line(points=default_line, feed=300, power=150, dynamic_power=True):
    prog.G0(X=points[:, 0][0], Y=points[:, 0][1])


line()
prog


<GCode>[cmds=1]

In [98]:
prog = GCode.GCode()


def line(points=default_line, feed=300, power=150, dynamic_power=True):
    prog.G0(X=points[:, 0][0], Y=points[:, 0][1])
    prog.G1(X=points[:, 1][0], Y=points[:, 1][1])


line()
prog


<GCode>[cmds=2]

In [99]:
prog = GCode.GCode()


def line(points=default_line, feed=300, power=150, dynamic_power=True):
    prog.G0(X=points[:, 0][0], Y=points[:, 0][1])

    if dynamic_power:
        prog.M4(S=power)
    else:
        prog.M4(S=power)

    for row_idx in range(1, points.shape[0]):
        prog.G1(X=points[row_idx, 0], Y=points[row_idx, 1])
    prog.M5()


line()
prog


<GCode>[cmds=4]

Draw a 10mm x 10mm square

In [100]:
square_static = np.array([[0, 0], [10, 0], [10, 10], [0, 10], [0, 0]])


In [101]:
prog = GCode.GCode()


def line(points=default_line, feed=300, power=150, dynamic_power=True):
    prog.G0(X=points[0, 0], Y=points[0, 0])

    if dynamic_power:
        prog.M4(S=power)
    else:
        prog.M4(S=power)

    for row_idx in range(1, points.shape[0]):
        prog.G1(X=points[row_idx, 0], Y=points[row_idx, 1])
    prog.M5()


line(points=square_static)
prog


<GCode>[cmds=7]

In [102]:
prog = GCode.GCode()
def line(points=default_line, feed=300, power=150, dynamic_power=True):
    prog.G0(X=points[:,0][0], Y=points[:,0][1])

    if dynamic_power:
        prog.M4(S=power)
    else:
        prog.M4(S=power)
dd        
    for row_idx in range(1, points.shape[0]):
        prog.G1(X=points[:,row_idx][0], Y=points[:,row_idx][1])
    prog.M5()
line()
prog

<GCode>[cmds=4]

In [103]:
default_line


array([[ 0,  0],
       [10,  5]])

In [106]:
np.eye(2) * default_line


array([[0., 0.],
       [0., 5.]])

In [107]:
default_line * np.eye(2)


array([[0., 0.],
       [0., 5.]])

In [161]:
np.eye(2)


array([[1., 0.],
       [0., 1.]])

In [162]:
A = np.array([[1, 1], [1, 1]])
A


array([[1, 1],
       [1, 1]])

In [163]:
A * default_line


array([[ 0,  0],
       [10,  5]])

In [164]:
default_line * A


array([[ 0,  0],
       [10,  5]])

In [165]:
B = np.array([[0, 1], [1, 1]])
B


array([[0, 1],
       [1, 1]])

In [166]:
B * default_line


array([[ 0,  0],
       [10,  5]])

In [167]:
default_line * B


array([[ 0,  0],
       [10,  5]])

In [168]:
for i in range(0, 2):
    for j in range(0, 2):
        A = np.array([[1, 1], [1, 1]])


In [169]:
A[i][j] = 0


In [170]:
print(A)


[[1 1]
 [1 0]]


(Remembering math from 2010...)

In [171]:
for i in range(0, 2):
    for j in range(0, 2):
        A = np.array([[1, 1], [1, 1]])
        A[i][j] = 0
        print(A)
        print(A * default_line)
        print(default_line * A)
        print("---------")


[[0 1]
 [1 1]]
[[ 0  0]
 [10  5]]
[[ 0  0]
 [10  5]]
---------
[[1 0]
 [1 1]]
[[ 0  0]
 [10  5]]
[[ 0  0]
 [10  5]]
---------
[[1 1]
 [0 1]]
[[0 0]
 [0 5]]
[[0 0]
 [0 5]]
---------
[[1 1]
 [1 0]]
[[ 0  0]
 [10  0]]
[[ 0  0]
 [10  0]]
---------


#&*@(*$.

In [172]:
np.matmul(A, default_line)


array([[10,  5],
       [ 0,  0]])

In [173]:
np.matmul(default_line, A)


array([[ 0,  0],
       [15, 10]])

In [174]:
default_line


array([[ 0,  0],
       [10,  5]])

In [175]:
np.matmul(A, default_line)


array([[10,  5],
       [ 0,  0]])

In [180]:
A


array([[1, 1],
       [1, 0]])