In [2]:
import configparser
import os
import sys
from time import sleep
from uuid import uuid4

import numpy as np

import GCode
import GRBL

# Laser Shading By adjusting focus on the Z-axis

# Code:

In [3]:
# Poplar 1x4". Cut
BlockHeight = 89.0  # [mm]
BlockLength = 2 * BlockHeight  # [mm]
BlockThickness = 19.0  # [mm]
print("{} x {} x {}".format(BlockHeight, BlockLength, BlockThickness))

89.0 x 178.0 x 19.0


In [4]:
def init(**kwargs):
    program = GCode.GCode(**kwargs)
    program.G0(F=500)
    program.G1(F=300)
    program.M3(S=1)
    program.G28()
    program.G21()  # Metric Units
    program.G90()  # Absolute positioning.
    program.G92(X=0, Y=0)
    program.M5()
    return program


def end(**kwargs):
    program = GCode.GCode(**kwargs)
    program.M5()
    return program


In [6]:
config = configparser.ConfigParser()
config["GRBL"] = dict()
config["GRBL"]["port"] = "/dev/cnc_3018"
cnc = GRBL.GRBL(**config["GRBL"])


In [9]:
cnc.reset()


(0, ['ok', '', "Grbl 1.1f ['$' for help]", "[MSG:'$H'|'$X' to unlock]", 'ok'])

In [11]:
if "Alarm" in cnc.status:
    print("Homing.")
    cnc.home()


Homing.


# Generate Program

Generate the G-code program that will test how the laser focus affects shading.

- Laser 'focused' at -14mm.
- Testing 17 positions between [-28, 0]
- Testing 3 different feed rates [100, 200, 300]
- Testing 5 different power settings between [100, 255]

In [12]:
# Define a gap between horizontal lines
vgap = 5 # [mm]
# Generate a list of horizontal line vertical coordinates
vs = np.arange( vgap, BlockHeight, vgap)
vs


array([ 5., 10., 15., 20., 25., 30., 35., 40., 45., 50., 55., 60., 65.,
       70., 75., 80., 85.])

In [13]:
# Define a horizontal distance to test lazerin.
hgap = 10 # [mm]
hs = np.arange(0, BlockLength, hgap)
hs


array([  0.,  10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.,
       110., 120., 130., 140., 150., 160., 170.])

In [14]:
# Total travel range, starts at ztravel, ends at 0. "negative space"(?)
ztravel = -28
# Generate a number of z-axis test positions.
# Each z-height will have 10 mm marked at the given feed rate and power.
zs = np.linspace(start=ztravel, stop=0, num=len(hs) - 1, endpoint=True)
zs


array([-28.  , -26.25, -24.5 , -22.75, -21.  , -19.25, -17.5 , -15.75,
       -14.  , -12.25, -10.5 ,  -8.75,  -7.  ,  -5.25,  -3.5 ,  -1.75,
         0.  ])

In [15]:
# Laser powers to test.
powers = np.linspace(100, 255, 5, endpoint=True, dtype=np.uint8)
powers


array([100, 138, 177, 216, 255], dtype=uint8)

In [16]:
program = GCode.GCode(machine=cnc)
program.G0(F=500)
program.G1(F=300)
program.M3(S=1)

feeds = [100, 200, 300]

for idx1, feed in enumerate(feeds):  # [mm/min]
    program.G1(F=feed)
    for idx2, power in enumerate(powers):
        program.M4(S=power)
        program.M5()
        
        v_idx = idx1 * len(feeds) + idx2
        Y = vs[v_idx]
        program.G0(X=hs[0], Y=Y)
        for idx3, z in enumerate(zs):
            x0 = hs[idx3]
            xf = hs[idx3 + 1]
            program.G0(Z=z, X=x0)
            program.M4(S=power)
            program.G1(X=xf, Y=Y, Z=z, F=feed)
            program.M5() # Laser. Off.
            break
        
        program.M5() # Laser. Off.
        break
        
    program.M5() # Laser. Off.
    break

In [17]:
program

<GCode>[cmds=13]

In [18]:
program.run()

^C
