In [2]:
import os
import sys
import time

import matplotlib.pyplot as plt
import numpy as np

import GCode
import GRBL


# Code:

In [22]:
points0 = np.array([
    [0,0],
    [10,0]
])

GCode.Line(points=points0)

Line<cut=10.0mm, F=300, S=150>

In [23]:
points10 = np.array([
    [0,10],
    [10,10]
])

GCode.Line(points=points10)

Line<cut=10.0mm, F=300, S=150>

In [24]:
prog = GCode.Program(lines=[
    GCode.Line(points=points0),
    GCode.Line(points=points10),
])

In [50]:
prog.generate_gcode()

In [51]:
prog.laserin_dist

20.0

In [52]:
prog.jog_dist

28.284271247461902

In [53]:
prog.lines

[Line<cut=10.0mm, F=300, S=150>, Line<cut=10.0mm, F=300, S=150>]

In [54]:
prog.lines[1].points

array([[ 0, 10],
       [10, 10]])

In [55]:
flip = np.array([[0, 1], [1, 0]])
np.matmul(flip, prog.lines[1].points)

array([[10, 10],
       [ 0, 10]])

In [56]:
np.matmul(flip, prog.lines[0].points)

array([[10,  0],
       [ 0,  0]])