In [2]:
import os
import sys
import time

import matplotlib.pyplot as plt
import numpy as np

import GCode
import GRBL


In [15]:
# Flip a 2D array. Effectively reversing the path.
flip2 = np.array([
    [0, 1],
    [1, 0],
])
flip2

array([[0, 1],
       [1, 0]])

In [17]:
# Flip a 2x3 array. Effectively reversing the path.
flip3 = np.array([
    [0, 0, 1],
    [0, 1, 0],
    [1, 0, 0],
])
flip3

array([[0, 0, 1],
       [0, 1, 0],
       [1, 0, 0]])

# Code:

Draw a 10 mm line from (0, 0) to (10, 0).

In [23]:
line_len = 10
line_n_points = 2

In [24]:
p = np.linspace(0, line_len, line_n_points, endpoint=True)
p

array([ 0., 10.])

In [26]:
line_n_points = 3
p = np.linspace(0, line_len, line_n_points, endpoint=True)
p

array([ 0.,  5., 10.])

In [27]:
line_n_points = 4
p = np.linspace(0, line_len, line_n_points, endpoint=True)
p

array([ 0.        ,  3.33333333,  6.66666667, 10.        ])

In [3]:
points = np.array([
    [0,0],
    [10,0]
])

GCode.Line(points=points)

Line<cut=10.0mm, F=300, S=150>

In [11]:
# Draw it twice.
lines = [GCode.Line(points=points, feed=120)]*2
prog0 = GCode.Program(lines=lines)
prog0

Program<lines=2>

In [12]:
lines = [GCode.Line(points=points, feed=120)]*2
prog1 = GCode.Program(lines=lines)
prog1.lines[1].points = np.matmul(flip, prog.lines[1].points)

Program<lines=2>

In [ ]:
progs = [prog0, prog1]

In [5]:
prog.generate_gcode()
prog

Program<lines=2>

In [41]:
prog.lines[1].points = np.matmul(flip, prog.lines[1].points)