In [28]:
import os
import sys
import time

import matplotlib.pyplot as plt
import numpy as np

import GCode
import GRBL


In [29]:
# Flip a 2D array. Effectively reversing the path.
flip2 = np.array([
    [0, 1],
    [1, 0],
])
flip2

array([[0, 1],
       [1, 0]])

In [30]:
# Flip a 2x3 array. Effectively reversing the path.
flip3 = np.array([
    [0, 0, 1],
    [0, 1, 0],
    [1, 0, 0],
])
flip3

array([[0, 0, 1],
       [0, 1, 0],
       [1, 0, 0]])

In [33]:
A = np.array([
    [1, 2], 
    [3, 4],
])
A

array([[1, 2],
       [3, 4]])

In [34]:
np.matmul(flip2, A)

array([[3, 4],
       [1, 2]])

In [36]:
B = np.array([
    [1, 2], 
    [3, 4],
    [5, 6],
])
B

array([[1, 2],
       [3, 4],
       [5, 6]])

In [37]:
np.matmul(flip3, B)

array([[5, 6],
       [3, 4],
       [1, 2]])

In [38]:
B.shape[0]

(3, 2)

In [39]:
np.eye(B.shape[0])

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [54]:
flip_n_reverseit = np.eye(B.shape[0])[:, ::-1]
flip_n_reverseit

array([[0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.]])

In [55]:
def reverse(self, points):
    flip_n_reverseit = np.eye(points.shape[0])[:, ::-1]
    
    return np.matmul(flip_n_reverseit, points)

In [58]:
reverse(None, B)

array([[5., 6.],
       [3., 4.],
       [1., 2.]])

# Code:

Draw a 10 mm line from (0, 0) to (10, 0).

In [59]:
line_len = 10
line_n_points = 2

In [60]:
p = np.linspace(0, line_len, line_n_points, endpoint=True)
p

array([ 0., 10.])

In [61]:
line_n_points = 3
p = np.linspace(0, line_len, line_n_points, endpoint=True)
p

array([ 0.,  5., 10.])

In [62]:
line_n_points = 4
p = np.linspace(0, line_len, line_n_points, endpoint=True)
p

array([ 0.        ,  3.33333333,  6.66666667, 10.        ])

In [65]:
p

array([ 0.        ,  3.33333333,  6.66666667, 10.        ])

In [66]:
Y=0
for X in np.linspace(0, line_len, line_n_points, endpoint=True):
    

array([ 0., 10.])

array([[ 0.        ,  0.        ],
       [ 0.        ,  3.33333333],
       [ 0.        ,  6.66666667],
       [ 0.        , 10.        ]])

In [80]:
def HorzLine(X0=0, Xf=10, Y=0, n_points=2):
    p = np.linspace(X0, Xf, n_points, endpoint=True)
    line_points = np.array([
        p,
        Y*np.ones(p.shape),
    ])
    return line_points.transpose()

In [84]:
HorzLine()

array([[ 0.        ,  0.        ],
       [ 0.20408163,  0.        ],
       [ 0.40816327,  0.        ],
       [ 0.6122449 ,  0.        ],
       [ 0.81632653,  0.        ],
       [ 1.02040816,  0.        ],
       [ 1.2244898 ,  0.        ],
       [ 1.42857143,  0.        ],
       [ 1.63265306,  0.        ],
       [ 1.83673469,  0.        ],
       [ 2.04081633,  0.        ],
       [ 2.24489796,  0.        ],
       [ 2.44897959,  0.        ],
       [ 2.65306122,  0.        ],
       [ 2.85714286,  0.        ],
       [ 3.06122449,  0.        ],
       [ 3.26530612,  0.        ],
       [ 3.46938776,  0.        ],
       [ 3.67346939,  0.        ],
       [ 3.87755102,  0.        ],
       [ 4.08163265,  0.        ],
       [ 4.28571429,  0.        ],
       [ 4.48979592,  0.        ],
       [ 4.69387755,  0.        ],
       [ 4.89795918,  0.        ],
       [ 5.10204082,  0.        ],
       [ 5.30612245,  0.        ],
       [ 5.51020408,  0.        ],
       [ 5.71428571,

In [64]:
progs = list()

for line_n_points in range(2, 5):
    progs.append(GCode.Program(GCode.Line(points=np.linspace(0, line_len, line_n_points, endpoint=True))))

progs

IndexError: too many indices for array

In [11]:
# Draw it twice.
lines = [GCode.Line(points=points, feed=120)]*2
prog0 = GCode.Program(lines=lines)
prog0

Program<lines=2>

In [12]:
lines = [GCode.Line(points=points, feed=120)]*2
prog1 = GCode.Program(lines=lines)
prog1.lines[1].points = np.matmul(flip, prog.lines[1].points)

Program<lines=2>

In [ ]:
progs = [prog0, prog1]

In [5]:
prog.generate_gcode()
prog

Program<lines=2>

In [41]:
prog.lines[1].points = np.matmul(flip, prog.lines[1].points)