In [28]:
import os
import sys
import time

import matplotlib.pyplot as plt
import numpy as np

import GCode
import GRBL


In [29]:
# Flip a 2D array. Effectively reversing the path.
flip2 = np.array([
    [0, 1],
    [1, 0],
])
flip2

array([[0, 1],
       [1, 0]])

In [30]:
# Flip a 2x3 array. Effectively reversing the path.
flip3 = np.array([
    [0, 0, 1],
    [0, 1, 0],
    [1, 0, 0],
])
flip3

array([[0, 0, 1],
       [0, 1, 0],
       [1, 0, 0]])

In [33]:
A = np.array([
    [1, 2], 
    [3, 4],
])
A

array([[1, 2],
       [3, 4]])

In [34]:
np.matmul(flip2, A)

array([[3, 4],
       [1, 2]])

In [36]:
B = np.array([
    [1, 2], 
    [3, 4],
    [5, 6],
])
B

array([[1, 2],
       [3, 4],
       [5, 6]])

In [37]:
np.matmul(flip3, B)

array([[5, 6],
       [3, 4],
       [1, 2]])

In [38]:
B.shape[0]

(3, 2)

In [39]:
np.eye(B.shape[0])

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [52]:
flip_n_reverseit = np.eye(B.shape[0])[:, ::-1]
flip_n_reverseit

# Code:

Draw a 10 mm line from (0, 0) to (10, 0).

In [23]:
line_len = 10
line_n_points = 2

In [24]:
p = np.linspace(0, line_len, line_n_points, endpoint=True)
p

array([ 0., 10.])

In [26]:
line_n_points = 3
p = np.linspace(0, line_len, line_n_points, endpoint=True)
p

array([ 0.,  5., 10.])

In [27]:
line_n_points = 4
p = np.linspace(0, line_len, line_n_points, endpoint=True)
p

array([ 0.        ,  3.33333333,  6.66666667, 10.        ])

In [3]:
points = np.array([
    [0,0],
    [10,0]
])

GCode.Line(points=points)

Line<cut=10.0mm, F=300, S=150>

In [11]:
# Draw it twice.
lines = [GCode.Line(points=points, feed=120)]*2
prog0 = GCode.Program(lines=lines)
prog0

Program<lines=2>

In [12]:
lines = [GCode.Line(points=points, feed=120)]*2
prog1 = GCode.Program(lines=lines)
prog1.lines[1].points = np.matmul(flip, prog.lines[1].points)

Program<lines=2>

In [ ]:
progs = [prog0, prog1]

In [5]:
prog.generate_gcode()
prog

Program<lines=2>

In [41]:
prog.lines[1].points = np.matmul(flip, prog.lines[1].points)