In [28]:
import os
import sys
import time

import matplotlib.pyplot as plt
import numpy as np

import GCode
import GRBL


In [29]:
# Flip a 2D array. Effectively reversing the path.
flip2 = np.array([
    [0, 1],
    [1, 0],
])
flip2

array([[0, 1],
       [1, 0]])

In [30]:
# Flip a 2x3 array. Effectively reversing the path.
flip3 = np.array([
    [0, 0, 1],
    [0, 1, 0],
    [1, 0, 0],
])
flip3

array([[0, 0, 1],
       [0, 1, 0],
       [1, 0, 0]])

In [33]:
A = np.array([
    [1, 2], 
    [3, 4],
])
A

array([[1, 2],
       [3, 4]])

In [34]:
np.matmul(flip2, A)

array([[3, 4],
       [1, 2]])

In [36]:
B = np.array([
    [1, 2], 
    [3, 4],
    [5, 6],
])
B

array([[1, 2],
       [3, 4],
       [5, 6]])

In [37]:
np.matmul(flip3, B)

array([[5, 6],
       [3, 4],
       [1, 2]])

In [38]:
B.shape[0]

(3, 2)

In [39]:
np.eye(B.shape[0])

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [54]:
flip_n_reverseit = np.eye(B.shape[0])[:, ::-1]
flip_n_reverseit

array([[0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.]])

In [55]:
def reverse(self, points):
    flip_n_reverseit = np.eye(points.shape[0])[:, ::-1]
    
    return np.matmul(flip_n_reverseit, points)

In [58]:
reverse(None, B)

array([[5., 6.],
       [3., 4.],
       [1., 2.]])

# Code:

Draw a 10 mm line from (0, 0) to (10, 0).

In [59]:
line_len = 10
line_n_points = 2

In [60]:
p = np.linspace(0, line_len, line_n_points, endpoint=True)
p

array([ 0., 10.])

In [61]:
line_n_points = 3
p = np.linspace(0, line_len, line_n_points, endpoint=True)
p

array([ 0.,  5., 10.])

In [62]:
line_n_points = 4
p = np.linspace(0, line_len, line_n_points, endpoint=True)
p

array([ 0.        ,  3.33333333,  6.66666667, 10.        ])

In [65]:
p

array([ 0.        ,  3.33333333,  6.66666667, 10.        ])

In [66]:
Y=0
for X in np.linspace(0, line_len, line_n_points, endpoint=True):
    

array([ 0., 10.])

array([[ 0.        ,  0.        ],
       [ 0.        ,  3.33333333],
       [ 0.        ,  6.66666667],
       [ 0.        , 10.        ]])

In [87]:
def HorzLine(X0=0, Xf=10, Y=0, n_points=2):
    p = np.linspace(X0, Xf, n_points, endpoint=True)
    line_points = np.array([
        p,
        Y*np.ones(p.shape),
    ])
    return line_points.transpose()
HorzLine()

array([[ 0.,  0.],
       [10.,  0.]])

In [89]:
def VertLine(X=0, Y0=0, Yf=10, n_points=2):
    p = np.linspace(Y0, Yf, n_points, endpoint=True)
    line_points = np.array([
        X*np.ones(p.shape),
        p,
    ])
    return line_points.transpose()
VertLine()

array([[ 0.,  0.],
       [ 0., 10.]])

In [92]:
points = HorzLine(X0=0, Xf=10, Y=0, n_points=2)
points

array([[ 0.,  0.],
       [10.,  0.]])

In [93]:
line = GCode.Line(points=points)
line

Line<cut=10.0mm, F=300, S=150>

In [94]:
line.__repr__()

'Line<cut=10.0mm, F=300, S=150>'

In [97]:
prog_cfg={
    "points": points
}
prog_cfg

numpy.ndarray

In [99]:
line_cfg = {
    "X0": 0,
    "Xf": 10,
    "Y": 0,
    "n_points": 2
}
line_cfg

{'X0': 0, 'Xf': 10, 'Y': 0, 'n_points': 2}

In [100]:
help(GCode.Line)

Help on class Line in module GCode.Line:

class Line(GCode.GCode.GCode)
 |  Method resolution order:
 |      Line
 |      GCode.GCode.GCode
 |      builtins.object
 |  
 |  Methods defined here:
 |  
 |  __init__(self, points=array([[ 0.        ,  0.        ],
 |         [17.32050808,  0.        ],
 |         [17.32050808, 10.        ],
 |         [ 0.        ,  0.        ]]), feed=300, power=150, dynamic_power=True, *args, **kwargs)
 |      Initialize self.  See help(type(self)) for accurate signature.
 |  
 |  __repr__(self)
 |      Return repr(self).
 |  
 |  generate_gcode(self)
 |  
 |  ----------------------------------------------------------------------
 |  Data descriptors defined here:
 |  
 |  X
 |  
 |  Y
 |  
 |  dist
 |      Total distance traveled.
 |  
 |  dists
 |      Distances traveled in each line segment
 |  
 |  time
 |      Total distance traveled.
 |  
 |  times
 |      Amount of time spent drawing each line spegment.
 |      
 |      Does not take into consider

In [103]:
help(GCode.Program)

Help on class Program in module GCode.Program:

class Program(GCode.GCode.GCode)
 |  A GCode Program Object
 |  
 |  Method resolution order:
 |      Program
 |      GCode.GCode.GCode
 |      builtins.object
 |  
 |  Methods defined here:
 |  
 |  __init__(self, lines=[], feed=120, *args, **kwargs)
 |      Initialize self.  See help(type(self)) for accurate signature.
 |  
 |  __repr__(self)
 |      Return repr(self).
 |  
 |  generate_gcode(self)
 |  
 |  setup(self)
 |  
 |  teardown(self)
 |  
 |  ----------------------------------------------------------------------
 |  Data descriptors defined here:
 |  
 |  dist
 |  
 |  jog_dist
 |  
 |  jog_time
 |      Return time spent jogging
 |  
 |  laserin_dist
 |      Distance, in mm, the line spends cutting.
 |  
 |  laserin_time
 |      Duration, in s, the line spends cutting.
 |  
 |  time
 |  
 |  ----------------------------------------------------------------------
 |  Methods inherited from GCode.GCode.GCode:
 |  
 |  G0 = cmd_fcn

In [102]:
progs = list()

for n_points in [2]: #range(2, 5):
    
    line_cfg = {
        "X0": 0,
        "Xf": 10,
        "Y": 0,
        "n_points": n_points
    }    
    points = HorzLine(**line_cfg)
    
    line_cfg = {
        "points": points,
        "feed":300,
        "power":150,
        "dynamic_power": True,
    }
    line = GCode.Line(points=points)
    
    
    prog_cfg={
        "lines": [line, line]
    }
    prog = GCode.Program(**prog_cfg)
    
    progs.append(GCode.Program(GCode.Line(points=np.linspace(0, line_len, line_n_points, endpoint=True))))

progs

TypeError: __init__() got an unexpected keyword argument 'points'

In [11]:
# Draw it twice.
lines = [GCode.Line(points=points, feed=120)]*2
prog0 = GCode.Program(lines=lines)
prog0

Program<lines=2>

In [12]:
lines = [GCode.Line(points=points, feed=120)]*2
prog1 = GCode.Program(lines=lines)
prog1.lines[1].points = np.matmul(flip, prog.lines[1].points)

Program<lines=2>

In [ ]:
progs = [prog0, prog1]

In [5]:
prog.generate_gcode()
prog

Program<lines=2>

In [41]:
prog.lines[1].points = np.matmul(flip, prog.lines[1].points)